-- Update cat characters to use images from public/cats directory
UPDATE cat_characters SET icon_url = '/cats/Angry cat.png' WHERE name = 'Angry Cat';
UPDATE cat_characters SET icon_url = '/cats/Ballet cat.jpg' WHERE name = 'Ballet Cat';
UPDATE cat_characters SET icon_url = '/cats/Chill cat.jpg' WHERE name = 'Chill Cat';
UPDATE cat_characters SET icon_url = '/cats/Dino cat.jpg' WHERE name = 'Dino Cat';
UPDATE cat_characters SET icon_url = '/cats/Drum cat.png' WHERE name = 'Drum Cat';
UPDATE cat_characters SET icon_url = '/cats/Flower cat.jpg' WHERE name = 'Flower Cat';
UPDATE cat_characters SET icon_url = '/cats/French cat.jpg' WHERE name = 'French Cat';
UPDATE cat_characters SET icon_url = '/cats/Glass cat.png' WHERE name = 'Glass Cat';
UPDATE cat_characters SET icon_url = '/cats/Happy cat.png' WHERE name = 'Happy Cat';
UPDATE cat_characters SET icon_url = '/cats/Jumper cat.jpg' WHERE name = 'Jumper Cat';
UPDATE cat_characters SET icon_url = '/cats/King cat.jpg' WHERE name = 'King Cat';
UPDATE cat_characters SET icon_url = '/cats/Lil Cat.png' WHERE name = 'Lil Cat';
UPDATE cat_characters SET icon_url = '/cats/Milk cat.jpg' WHERE name = 'Milk Cat';
UPDATE cat_characters SET icon_url = '/cats/Orange cat.png' WHERE name = 'Orange Cat';
UPDATE cat_characters SET icon_url = '/cats/Pirate cat.png' WHERE name = 'Pirate Cat';
UPDATE cat_characters SET icon_url = '/cats/Robo arm cat.png' WHERE name = 'Robo Arm Cat';
UPDATE cat_characters SET icon_url = '/cats/Science cat.jpg' WHERE name = 'Science Cat';
UPDATE cat_characters SET icon_url = '/cats/Sick cat.jpg' WHERE name = 'Sick Cat';
UPDATE cat_characters SET icon_url = '/cats/Silly cat.jpg' WHERE name = 'Silly Cat';
UPDATE cat_characters SET icon_url = '/cats/Tomato cat.jpg' WHERE name = 'Tomato Cat';
UPDATE cat_characters SET icon_url = '/cats/Tuff cat.jpg' WHERE name = 'Tuff Cat';
UPDATE cat_characters SET icon_url = '/cats/auracat.png' WHERE name = 'Aura Cat';