-- Insert base Would You Rather questions
INSERT INTO public.would_you_rather_questions (option_a, option_b, category) VALUES
('Have the ability to read minds', 'Have the ability to teleport anywhere instantly', 'general'),
('Always have to tell the truth', 'Always have to lie', 'general'),
('Be able to speak all languages fluently', 'Be able to talk to animals', 'general'),
('Have super strength', 'Have the ability to become invisible', 'general'),
('Live without the internet for a year', 'Live without your phone for a year', 'general'),
('Always be 10 minutes late', 'Always be 20 minutes early', 'general'),
('Have a rewind button for your life', 'Have a pause button for your life', 'general'),
('Be famous but broke', 'Be unknown but wealthy', 'general'),
('Only be able to whisper', 'Only be able to shout', 'general'),
('Have the worst job ever but make millions', 'Have your dream job but make minimum wage', 'general'),
('Be able to fly but only 5 feet off the ground', 'Be able to run 100mph but only in one direction', 'general'),
('Have taste buds in your fingers', 'Have taste buds on your feet', 'general'),
('Always know when someone is lying', 'Always get away with lying', 'general'),
('Have unlimited money but can never leave your hometown', 'Have no money but can travel anywhere for free', 'general'),
('Be able to control time', 'Be able to control the weather', 'general'),
('Have pizza as your only food forever', 'Never be able to eat pizza again', 'general'),
('Be stuck in a room with your worst enemy for 24 hours', 'Be stuck alone in a room for a week', 'general'),
('Have x-ray vision that you cannot turn off', 'Have super hearing that you cannot turn off', 'general'),
('Always have to dance instead of walk', 'Always have to sing instead of talk', 'general'),
('Live in a world without music', 'Live in a world without movies', 'general'),
('Be able to see 10 years into the future', 'Be able to go back 10 years in the past', 'general'),
('Have a personal chef', 'Have a personal chauffeur', 'general'),
('Be trapped in a romantic comedy', 'Be trapped in a horror movie', 'general'),
('Always have to wear formal clothes', 'Always have to wear pajamas', 'general'),
('Have the ability to heal others', 'Have the ability to never get hurt yourself', 'general');

-- Insert additional base Paranoia questions
INSERT INTO public.paranoia_questions (question, category, spiciness_level) VALUES
('Who is most likely to become famous on social media?', 'general', 1),
('Who is most likely to survive longest in a zombie apocalypse?', 'general', 2),
('Who is most likely to win a million dollars and spend it all in a week?', 'general', 2),
('Who is most likely to become a professional chef?', 'general', 1),
('Who is most likely to get lost in their own neighborhood?', 'general', 1),
('Who is most likely to start a successful business?', 'general', 1),
('Who is most likely to become a superhero?', 'general', 1),
('Who is most likely to cry during a kids movie?', 'general', 1),
('Who is most likely to eat something past its expiration date?', 'general', 2),
('Who is most likely to become a world traveler?', 'general', 1),
('Who is most likely to accidentally send a text to the wrong person?', 'general', 2),
('Who is most likely to win a dance competition?', 'general', 1),
('Who is most likely to become a professional athlete?', 'general', 1),
('Who is most likely to forget their own birthday?', 'general', 2),
('Who is most likely to become a teacher?', 'general', 1),
('Who is most likely to go skydiving?', 'general', 2),
('Who is most likely to become a YouTube star?', 'general', 1),
('Who is most likely to sleep through an important event?', 'general', 2),
('Who is most likely to become president?', 'general', 1),
('Who is most likely to get a tattoo they regret?', 'general', 2),
('Who is most likely to win a karaoke contest?', 'general', 1),
('Who is most likely to become a millionaire?', 'general', 1),
('Who is most likely to get arrested for something silly?', 'general', 3),
('Who is most likely to move to another country?', 'general', 1),
('Who is most likely to become a motivational speaker?', 'general', 1);