-- Update cat characters to use images from public/cats/ folder
UPDATE cat_characters SET icon_url = '/cats/Angry cat.png' WHERE name = 'Angry cat';
UPDATE cat_characters SET icon_url = '/cats/Ballet cat.jpg' WHERE name = 'Ballet cat';
UPDATE cat_characters SET icon_url = '/cats/Chill cat.jpg' WHERE name = 'Chill cat';
UPDATE cat_characters SET icon_url = '/cats/Dino cat.jpg' WHERE name = 'Dino cat';
UPDATE cat_characters SET icon_url = '/cats/Drum cat.png' WHERE name = 'Drum cat';
UPDATE cat_characters SET icon_url = '/cats/Flower cat.jpg' WHERE name = 'Flower cat';
UPDATE cat_characters SET icon_url = '/cats/French cat.jpg' WHERE name = 'French cat';
UPDATE cat_characters SET icon_url = '/cats/Glass cat.png' WHERE name = 'Glass cat';
UPDATE cat_characters SET icon_url = '/cats/Happy cat.png' WHERE name = 'Happy cat';
UPDATE cat_characters SET icon_url = '/cats/Jumper cat.jpg' WHERE name = 'Jumper cat';
UPDATE cat_characters SET icon_url = '/cats/King cat.jpg' WHERE name = 'King cat';
UPDATE cat_characters SET icon_url = '/cats/Lil Cat.png' WHERE name = 'Lil Cat';
UPDATE cat_characters SET icon_url = '/cats/Milk cat.jpg' WHERE name = 'Milk cat';
UPDATE cat_characters SET icon_url = '/cats/Orange cat.png' WHERE name = 'Orange cat';
UPDATE cat_characters SET icon_url = '/cats/Pirate cat.png' WHERE name = 'Pirate cat';
UPDATE cat_characters SET icon_url = '/cats/Robo arm cat.png' WHERE name = 'Robo arm cat';
UPDATE cat_characters SET icon_url = '/cats/Science cat.jpg' WHERE name = 'Science cat';
UPDATE cat_characters SET icon_url = '/cats/Sick cat.jpg' WHERE name = 'Sick cat';
UPDATE cat_characters SET icon_url = '/cats/Silly cat.jpg' WHERE name = 'Silly cat';
UPDATE cat_characters SET icon_url = '/cats/Tomato cat.jpg' WHERE name = 'Tomato cat';
UPDATE cat_characters SET icon_url = '/cats/Tuff cat.jpg' WHERE name = 'Tuff cat';
UPDATE cat_characters SET icon_url = '/cats/auracat.png' WHERE name = 'auracat';