-- Insert cat characters with their corresponding images from public/cats
INSERT INTO cat_characters (name, icon_url, description, stats) VALUES
('Angry Cat', '/cats/Angry cat.png', 'A feisty feline with attitude', '{"speed": 2, "stealth": 1, "charisma": 1, "strength": 3, "intelligence": 2}'),
('Ballet Cat', '/cats/Ballet cat.jpg', 'Graceful and elegant dancer', '{"speed": 3, "stealth": 2, "charisma": 3, "strength": 1, "intelligence": 2}'),
('Chill Cat', '/cats/Chill cat.jpg', 'Laid back and relaxed', '{"speed": 1, "stealth": 3, "charisma": 2, "strength": 1, "intelligence": 3}'),
('Dino Cat', '/cats/Dino cat.jpg', 'Prehistoric feline friend', '{"speed": 2, "stealth": 1, "charisma": 2, "strength": 3, "intelligence": 2}'),
('Drum Cat', '/cats/Drum cat.png', 'Musical rhythm master', '{"speed": 2, "stealth": 1, "charisma": 3, "strength": 2, "intelligence": 2}'),
('Flower Cat', '/cats/Flower cat.jpg', 'Nature loving gentle soul', '{"speed": 1, "stealth": 2, "charisma": 3, "strength": 1, "intelligence": 3}'),
('French Cat', '/cats/French cat.jpg', 'Sophisticated and cultured', '{"speed": 2, "stealth": 2, "charisma": 3, "strength": 1, "intelligence": 3}'),
('Glass Cat', '/cats/Glass cat.png', 'Transparent and mysterious', '{"speed": 3, "stealth": 3, "charisma": 1, "strength": 1, "intelligence": 2}'),
('Happy Cat', '/cats/Happy cat.png', 'Always cheerful and optimistic', '{"speed": 2, "stealth": 1, "charisma": 3, "strength": 2, "intelligence": 2}'),
('Jumper Cat', '/cats/Jumper cat.jpg', 'Athletic and energetic', '{"speed": 3, "stealth": 2, "charisma": 2, "strength": 2, "intelligence": 1}'),
('King Cat', '/cats/King cat.jpg', 'Royal and commanding', '{"speed": 1, "stealth": 1, "charisma": 3, "strength": 2, "intelligence": 3}'),
('Lil Cat', '/cats/Lil Cat.png', 'Small but mighty', '{"speed": 3, "stealth": 3, "charisma": 2, "strength": 1, "intelligence": 1}'),
('Milk Cat', '/cats/Milk cat.jpg', 'Pure and innocent', '{"speed": 1, "stealth": 2, "charisma": 3, "strength": 1, "intelligence": 3}'),
('Orange Cat', '/cats/Orange cat.png', 'Vibrant and energetic', '{"speed": 2, "stealth": 1, "charisma": 2, "strength": 2, "intelligence": 3}'),
('Pirate Cat', '/cats/Pirate cat.png', 'Adventurous seafarer', '{"speed": 2, "stealth": 3, "charisma": 2, "strength": 3, "intelligence": 1}'),
('Robo Arm Cat', '/cats/Robo arm cat.png', 'Tech-enhanced feline', '{"speed": 1, "stealth": 1, "charisma": 1, "strength": 3, "intelligence": 3}'),
('Science Cat', '/cats/Science cat.jpg', 'Brilliant researcher', '{"speed": 1, "stealth": 2, "charisma": 1, "strength": 1, "intelligence": 3}'),
('Sick Cat', '/cats/Sick cat.jpg', 'Needs extra care and love', '{"speed": 1, "stealth": 1, "charisma": 3, "strength": 1, "intelligence": 2}'),
('Silly Cat', '/cats/Silly cat.jpg', 'Playful and goofy', '{"speed": 2, "stealth": 1, "charisma": 3, "strength": 1, "intelligence": 1}'),
('Tomato Cat', '/cats/Tomato cat.jpg', 'Fresh and healthy', '{"speed": 2, "stealth": 2, "charisma": 2, "strength": 2, "intelligence": 2}'),
('Tuff Cat', '/cats/Tuff cat.jpg', 'Strong and resilient', '{"speed": 1, "stealth": 1, "charisma": 1, "strength": 3, "intelligence": 2}'),
('Aura Cat', '/cats/auracat.png', 'Mystical and ethereal', '{"speed": 2, "stealth": 3, "charisma": 2, "strength": 1, "intelligence": 3}');